### ISSUE TITLE
Ability to name Variables

### ISSUE THREAD

**Issue by briandconnelly** [yoavram/Plato#1]
Right now, *Strain* is hard-coded, but it might be nice to type in the name of the variable for other instances (e.g., different growth medium, different dilution, etc.).

**Comment by yoavram** [comment]
Yes I agree this is a must.

**Comment by yoavram** [comment]
@briandconnelly would you like to see the dev version of this feature and let me know if you think it is good enough for production? It's at http://development.plato-ui.divshot.io/

**Comment by briandconnelly** [comment]
Looks really good! Do you think it's worth checking to see if a value is given more than once?

The download button didn't work for me, but maybe that's just the development setup?

**Comment by yoavram** [comment]
@briandconnelly you mean if a value appears twice in the color palette? 
The download should work, which browser are you using? (I only tested on chrome on Windows, Ubuntu and Android).

**Comment by yoavram** [comment]
I've updated the development website. If you have duplicate values in the color palette you will get a warning and the table will not update.

**Comment by yoavram** [comment]
@briandconnelly could you see if the download button works for you in the production site http://plato.yoavram.com? 
Also, which browser and operating system are you using?

**Comment by briandconnelly** [comment]
Yep, the download button works fine on the production site. Using Safari on OS X Yosemite.

As for the previous comment, it looks like you've already handled the duplicate values!

**Comment by yoavram** [comment]
I'll check it -- I don't have Safari but I think I can use browserstack to emulate one.

Yes, I did! Thanks for the suggestion.

**Comment by yoavram** [comment]
@briandconnelly I used browserstack to view the dev website on Safari8/Yosemite. It worked. The file wasn't downloaded like in Chrome/Firefox (Safari doesn't support the HTML `download` attribute) but it did open in the same tab. 
I'll add a `target='_blank'` so that it will open in a new tab and will merge to master and depoly to production. If you still can't use the download button in production after that could you try to describe the failure? Maybe open the developer tools and see what's going on? 10x.

![bs_macyos_safari_8 0](https://cloud.githubusercontent.com/assets/1288133/7467640/a5042f0c-f305-11e4-9d7d-16d95ab55ccc.jpg)

**Comment by briandconnelly** [comment]
The button works for me now
