### ISSUE TITLE
Support multiple variables

### ISSUE THREAD

**Issue by briandconnelly** [yoavram/Plato#3]
This is where it gets more complicated, but I usually have multiple experimental variables on the same microtiter plate. It'd be great if plato supported this.

That ruins the nice color coding system, unfortunately. Maybe different fill types or something similar could be used.

**Comment by yoavram** [comment]
I think that a "better" solution is to make a different plate map for every manipulated condition (so one for strain, one for treatment, one for medium, etc.) and merge them later in the analysis (pandas: `pd.merge`...). 
Of course to do this one should be able to change the variable name as in #1.
@briandconnelly if you agree close the issue, otherwise leave it open.
